platzigram/platzigram/urls.py
from django.contrib import admin
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from platzigram.views import hello_world, say_hi, sortedIntegers
from posts import views as posts_views
from users import views as users_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('hello-world/', hello_world, name='hello_world'),
    path('sorted/', sortedIntegers, name='sort'),
    path('hi/<str:name>/<int:age>/', say_hi, name='hi'),

    path('', include(('posts.urls', 'posts'), namespace='posts')),
    #Zipping all routes in file url.py in posts folder
    #path('', posts_views.list_posts, name='feed'),#Path from posts app - folder created
    #path('posts/new', posts_views.create_post, name='create_post'),

    path('users/', include(('users.urls', 'users'), namespace='users')),
    #Zipping all routes in file url.py in users folder
    #path('users/login', users_views.login_view, name='login'),
    #path('users/logout', users_views.logout_view, name='logout'),
    #path('users/signup', users_views.signup, name='signup'),
    #path('users/me/profile', users_views.update_profile, name='update_profile')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

platzigram/posts/urls.py
from django.urls import path

#Views
from posts import views

urlpatterns = [
    path (
        route = '',
        view = views.list_posts,
        name='feed'
    ),
    path(
        route = 'posts/new/',
        view = views.create_post,
        name='create_post'
    ),
]

platzigram/users/urls.py
#Django
from django.urls import path
from django.views.generic import TemplateView

#Views
from users import views

urlpatterns = [
    #Posts


    #Management
    path(
        route='login/',
        view=views.login_view,
        name='login'),
    path(
        route='logout/',
        view=views.logout_view,
        name='logout'),
    path(
        route='signup/',
        view=views.signup,
        name='signup'),
    path(
        route='me/profile/',
        view=views.update_profile,
        name='update_profile'),
]

platzigram/users/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User

class Profile(models.Model):
    """ Proxy model that extends the base data with another information """
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.URLField(max_length=200, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)

    picture = models.ImageField(upload_to='static/img',
                                blank=True,
                                null=True)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """ Return username """
        return self.user.username

platzigram/users/forms.py
""" User forms"""

#Django
from django import forms

#Models
from django.contrib.auth.models import User
from users.models import Profile

class SignupForm(forms.Form):
    """SignUp Form"""

    username = forms.CharField(min_length=4, max_length=50)

    password = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput())
    password_confirmation = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput())

    first_name = forms.CharField(min_length=2, max_length=50)
    last_name = forms.CharField(min_length=2, max_length=50)

    email = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.EmailInput()
    )

    def clean_username(self):
        """Username must be unique - Cleaned data bring data readed after clicked button"""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use.')
        return username

    def clean(self):
        """Verify password confirmation match"""
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Password do not match.')

        return data

    def save(self):
        """Create user and profile"""
        data = self.cleaned_data
        data.pop('password_confirmation') #Quit password confirmation

        user = User.objects.create_user(**data) #Adding all fields to create user
        profile = Profile(user=user)
        profile.save()


class ProfileForm(forms.Form):
    """Profile forms"""
    website = forms.URLField(max_length=200, required=True)
    biography = forms.CharField(max_length=500, required=False)
    phone_number = forms.CharField(max_length=20, required=False)
    picture = forms.ImageField()

platzigram/users/views.py
""" Users views """
#Django
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

#Excepcions
from django.db.utils import IntegrityError

#Models
from django.contrib.auth.models import User

from users.models import Profile

#Forms
from users.forms import ProfileForm, SignupForm


def login_view(request):
    """Login view"""
    if request.method == 'POST':

        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect('posts:feed') #Acording to name used in urls.py
        else:
            return render(request, 'users/login.html', {'error': 'Invalid username and password'})

    return render(request, 'users/login.html')

@login_required
def update_profile(request):
    profile = request.user.profile

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.cleaned_data
            profile.website = data['website']
            profile.phone_number = data['phone_number']
            profile.biography = data['biography']
            profile.picture = data['picture']
            profile.save()

            return redirect('update_profile') #Each form is sent, we need to redirect URL, or each time we reload, form will send
    else:
        form = ProfileForm()

    return render(
        request=request,
        template_name='users/update_profile.html',
        context={
            'profile': profile,
            'user': request.user,
            'form': form
        }
    )

# Create your views here.

def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:login')
    else:
        form = SignupForm()
    return render(
        request= request,
        template_name='users/signup.html',
        context={'form':form}
    )
    #Last form validation - Not recommend validation in views
    # if request.method == 'POST':
    #     username = request.POST['username']
    #     passwd = request.POST['passwd']
    #     passwd_confirmation = request.POST['passwd_confirmation']
    #
    #     if passwd != passwd_confirmation:
    #         return render(request, 'users/signup.html', {'error': 'Passwords does not match'})
    #
    #     #Here the user is created
    #     try:
    #         user = User.objects.create_user(username=username, password=passwd)
    #     except IntegrityError:
    #         return render(request, 'users/signup.html', {'error': 'This username already exists'})
    #     #After, we add the other data
    #     user.first_name = request.POST['first_name']
    #     user.last_name = request.POST['last_name']
    #     user.email = request.POST['email']
    #     user.save()
    #
    #     profile = Profile(user=user)
    #     profile.save() #If we don't user Profile.object.Create_user, we need to put save in another line
    #
    #     return redirect('login')

    #return render(request, 'users/signup.html')

@login_required()
def logout_view(request):
    """ Logout a user"""
    logout(request)
    return redirect('users:login')

platzigram/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>
<body class="h-100">
    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">
                <img src="{% static "img/instagram.png" %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">

                {% block container %}{% endblock%}
            </div>
        </div>
    </div>
</body>
</html>

platzigram/templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
    <title>@{{ user.username }} | Platzigram</title>
{% endblock %}

{%  block container %}
    <div class="container mb-5" style="margin-top: 8em;">
        <div class="row">
            <div class="col-sm-4 d-flex justify-content-center">

            </div>
        </div>
    </div>
{% endblock %}

platzigram/templates/users/login.html
{% extends "users/base.html" %}

{% block head_content %}
    <title>Platzigram sign in</title>
{% endblock %}

{% block container %}

    {% if error %}
        <p class="alert alert-danger">{{ error }}</p>
    {% endif %}

    <form method="POST" action="{% url "users:login" %}">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" type="text" placeholder="Username" name="username" />
        </div>

        <div class="form-group">
            <input class="form-control" type="password" placeholder="Password" name="password" />
        </div>

        <button class="btn btn-primary btn-block mt-5" type="submit">Sign in</button>

    </form>

    <p class="mt-4">Don't have an account yet? <a href="{% url "users:signup" %}">Sign up here!</a></p>
{% endblock %}

platzigram/templates/users/signup.html
{% extends "users/base.html" %}

{% block head_content %}
    <title></title>
{% endblock %}

{% block container %}

    {% if error %}
        <p class="alert alert-danger">{{ error }}</p>
    {% endif %}

    <form action="{%  url 'users:signup' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        {% comment %}<div class="form-group">
            <input type="text" class="form-control" placeholder="Username" name="username" required="required" />
        </div>
        <div class="form-group">
            <input type="password" class="form-control" placeholder="Password" name="passwd" required="required" />
        </div>
        <div class="form-group">
            <input type="password" class="form-control" placeholder="Password confirmation" name="passwd_confirmation" required="required" />
        </div>
        <div class="form-group">
            <input type="text" class="form-control" placeholder="First name" name="first_name" required="required" />
        </div>
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Last name" name="last_name" required="required" />
        </div>
        <div class="form-group">
            <input type="email" class="form-control" placeholder="Email address" name="email" required="required" />
        </div>{% endcomment %}
        <button class="btn btn-primary btn-block mt-5" type="submit">Register!</button>
    </form>
    <p class="mt-4">Do yo want to Log in? <a href="{% url "users:login" %}">Log in here!</a></p>
{% endblock %}

platzigram/templates/users/update_profile.html
{% extends "base.html" %}

{% block head_content %}
    <title>@{{ request.user.username }} | Update profile</title>
{% endblock %}

{% block container %}
    <div class="row justify-content-md-center">
        <div class="col-6 p-4">
            <form action="{% url 'users:update_profile' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="media">
                    {% load static %}
                    
                    {% if profile.picture  %}
                        <img src="{{ profile.picture.url }}" class="rounded-circle" height="50" />
                    {% else %}
                        <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50" />
                    {% endif %}


                    <div class="media-body">
                        <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
                        <p class="ml-4"><input type="file" name="picture" /></p>
                    </div>
                </div>

                {% for error in form.picture.errors %}
                    <div class="alert alert-danger">
                        <b>Picture: </b>{{ error }}
                    </div>
                {% endfor %}

                <hr><br>

                <div class="form-group">
                    <label>Website</label>
                    <input type="text"
                           class="form-control {% if form.website.errors %}is-invalid{% endif %}"
                           name="website"
                           placeholder="Website"
                           value="{% if form.errors %}{{ form.website.value }}{% else %}{{ profile.website }}{% endif %}" />
                    <div class="div invalid-feedback">
                        {% for error in form.website.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>

                <div class="form-group">
                {# Logic to put square red when error and to hold correct value or put the new value (with error) #}
                    <label>Biography</label>
                    <textarea name="biography"
                              class="form-control {% if form.biography.errors %}is-invalid{% endif %}"
                    >{% if form.errors %}{{ form.biography.value }}{% else %}{{ profile.biography }}{% endif %}</textarea>
                {# Text above to show error #}
                    <div class="div invalid-feedback">
                        {% for error in form.biography.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>


                <div class="form-group">
                    <label>Phone number</label>
                    <input type="text"
                           class="form-control {% if form.phone_number.errors %}is-invalid{% endif %}"
                           name="phone_number"
                           placeholder="Phone number"
                           value="{% if form.errors %}{{ form.phone_number.value }}{% else %}{{ profile.phone_number }}{% endif %}" />
                    <div class="div invalid-feedback">
                        {% for error in form.phone_number.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>

                <button type="submit" class="btn btn-primary btn-block mt-5">Update info</button>
            </form>
        </div>
    </div>

{% endblock %}